// Generated by CoffeeScript 1.6.3
(function() {
  var App, myApp;

  App = (function() {
    App.prototype.parent = null;

    function App(aParent) {
      console.log('creating ...');
      this.addNavBar();
      this.parent = aParent;
    }

    App.prototype.initEvents = function() {
      return alert('init events');
    };

    App.prototype.addNavBar = function() {
      return $.ajax({
        url: "navBar.html",
        mimeType: "text/plain",
        success: function(data) {
          $('body').append(data);
          return $(document).foundation();
        }
      });
    };

    return App;

  })();

  myApp = new App;

}).call(this);
