// Generated by CoffeeScript 1.6.3
(function() {
  var App, myApp;

  App = (function() {
    App.prototype.parent = null;

    function App(parent) {
      this.parent = parent;
      console.log('creating ...');
      this.addNavBar();
    }

    App.prototype.initEvents = function() {
      return alert('init events');
    };

    App.prototype.addNavBar = function() {
      var myParent;
      myParent = this.parent;
      return $.ajax({
        url: "navBar.html",
        mimeType: "text/plain",
        success: function(data) {
          myParent.append(data);
          return $(document).foundation();
        }
      });
    };

    return App;

  })();

  myApp = new App($('body'));

}).call(this);
